[package]
name = "add_numbers_via_wavm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name="adding_lib"
path="src/adding.rs"
crate-type=["cdylib"]

